### ISSUE TITLE
xmpp deps error

### ISSUE THREAD

**Issue by siddhant3030** [gabrielgatu/elixible#1]
I'm using the library for a personal project. I'm trying to use this dependency 

 {:xmpp_mapper, git: "https://github.com/gabrielgatu/xmpp_mapper"}

But it's leading me to error and I'm not able to access this project. Can you point me to the right direction?

I'm using  {:phoenix, "~> 1.5.1"}

and

  [
      version: "0.1.0",
      elixir: "~> 1.7",
  ]

getting all this error 

` mix compile                                                                          ░▒▓ ✔ | at 16:12:46 
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/apple/Desktop/client/deps/xmpp_mapper/mix.exs:10: XmppMapper.Mixfile.project/0

===> Compiling p1_utils
===> Compiling stringprep
===> Compiling fast_xml
==> xmpp_mapper
Compiling 4 files (.erl)
src/jlib.erl:311: syntax error before: '/'
src/jlib.erl:321: syntax error before: '/'
src/jlib.erl:377: syntax error before: '/'
src/jlib.erl:395: syntax error before: '/'
src/jlib.erl:413: syntax error before: '/'
src/jlib.erl:433: syntax error before: '/'
could not compile dependency :xmpp_mapper, "mix compile" failed. You can recompile this dependency with "mix deps.compile xmpp_mapper", update it with "mix deps.update xmpp_mapper" or clean it with "mix deps.clean xmpp_mapper"

 ~/De/client | on master !3 ?8 ▓▒░ mix compile                                                                  ░▒▓ 1 х | took 13s | at 16:13:04 
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/apple/Desktop/client/deps/xmpp_mapper/mix.exs:10: XmppMapper.Mixfile.project/0

Unchecked dependencies for environment dev:
* xmpp_mapper (https://github.com//gabrielgatu/xmpp_mapper.git)
  lock outdated: the lock is outdated compared to the options in your mix.exs. To fetch locked version run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies

 ~/Desktop/client | on master !3 ?8 ▓▒░ deps.get                                                                           ░▒▓ 1 х | at 16:13:21 
zsh: command not found: deps.get

 ~/Desktop/client | on master !3 ?8 ▓▒░ mix deps.get                                                                     ░▒▓ 127 х | at 16:13:44 
* Updating xmpp_mapper (https://github.com/https://github.com//gabrielgatu/xmpp_mapper.git.git)
remote: Not Found
fatal: repository 'https://github.com/https://github.com//gabrielgatu/xmpp_mapper.git.git/' not found
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed

 ~/Desktop/client | on master !3 ?8 ▓▒░ mix deps.get                                                                       ░▒▓ 1 х | at 16:13:50 
* Updating xmpp_mapper (https://github.com//gabrielgatu/xmpp_mapper.git)
fatal: unable to access 'https://github.com//gabrielgatu/xmpp_mapper.git/': The requested URL returned error: 400
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed

**Comment by gabrielgatu** [comment]
Hey!
It seems like the dependency format is wrong: your git deps url need to finish with a .git extension, as stated in the docs: https://hexdocs.pm/mix/Mix.Tasks.Deps.html.

However consider that this "library" is not maintained anymore and its dependencies are outdated. It has been a good learning project but was never intended to be used as a production library, as stated in the README.

I highly suggest you going through the source code and forking it if necessary :)
